### PR TITLE
Promises for data tasks

### PR DESCRIPTION
**Pull request by mmmilo**
Adding support for Promises with `NSURLSessionDataTask` methods.

### CODE REVIEW

**Comment by XBeg9** [comment]
+1

**Comment by mmmilo** [comment]
@csotiriou Any chance this can be merged?

**Comment by csotiriou** [comment]
Support for this had been around for two months now, using a different but more clear methodology and API. I don't think this should be merged.

**Comment by mmmilo** [comment]
Yes, these changes aren't in sync with your "new" API.

But my changes allowed you to have access to the raw NSURLRequest (for complicated requests) as well as NSProgress.

**Comment by csotiriou** [comment]
You are right. I am performing a merge now. better late than never.

**Pull request merged**
